name = "gamerscraft"
main = "src/worker.js"
compatibility_date = "2024-09-01"

# Serve Vite build output directory
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
ENVIRONMENT = "production"
