/**
 * Cloudflare Worker Entrypoint for GamersCraft
 * Serves static assets generated by Vite in ./dist with SPA fallback and edge performance.
 */
export default {
    async fetch(request, env) {
        // Forward all static asset and page requests to the ASSETS binding
        if (env.ASSETS) {
            return env.ASSETS.fetch(request);
        }
        return new Response("GamersCraft: Assets binding not found.", { status: 404 });
    }
};
